# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: speech_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'speech_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14speech_service.proto\x12\x06speech\"u\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x0b\n\x03uid\x18\x03 \x01(\t\x12\x10\n\x08\x62uddy_id\x18\x04 \x01(\t\x12\x1d\n\x15\x61\x63tive_reminders_text\x18\x05 \x01(\t\"i\n\rAudioResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x18\n\x10transcribed_text\x18\x02 \x01(\t\x12\x14\n\x0cllm_response\x18\x03 \x01(\t\x12\x14\n\x0ctrigger_call\x18\x04 \x01(\x08\x32S\n\rSpeechService\x12\x42\n\rProcessSpeech\x12\x14.speech.AudioRequest\x1a\x15.speech.AudioResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speech_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=32
  _globals['_AUDIOREQUEST']._serialized_end=149
  _globals['_AUDIORESPONSE']._serialized_start=151
  _globals['_AUDIORESPONSE']._serialized_end=256
  _globals['_SPEECHSERVICE']._serialized_start=258
  _globals['_SPEECHSERVICE']._serialized_end=341
# @@protoc_insertion_point(module_scope)
