// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy-3yTnshcAiJuPyHf1IHNsT8tQX4EY9I',
    appId: '1:877436752472:web:915b09eee19b21a33d702d',
    messagingSenderId: '877436752472',
    projectId: 'buddyfinal2437',
    authDomain: 'buddyfinal2437.firebaseapp.com',
    storageBucket: 'buddyfinal2437.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPSOOD66-F3hQ8JFyr8MFNADYurxMsdZ4',
    appId: '1:877436752472:android:d064f784bea592fb3d702d',
    messagingSenderId: '877436752472',
    projectId: 'buddyfinal2437',
    storageBucket: 'buddyfinal2437.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPJlS1w6eXoUIiub986eGYUTLiq0wbN6I',
    appId: '1:877436752472:ios:5f6d02ed05fc6b593d702d',
    messagingSenderId: '877436752472',
    projectId: 'buddyfinal2437',
    storageBucket: 'buddyfinal2437.firebasestorage.app',
    iosClientId: '877436752472-gk0t46596u0jptfhoelcipfr994ujso4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPJlS1w6eXoUIiub986eGYUTLiq0wbN6I',
    appId: '1:877436752472:ios:5f6d02ed05fc6b593d702d',
    messagingSenderId: '877436752472',
    projectId: 'buddyfinal2437',
    storageBucket: 'buddyfinal2437.firebasestorage.app',
    iosClientId: '877436752472-gk0t46596u0jptfhoelcipfr994ujso4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy-3yTnshcAiJuPyHf1IHNsT8tQX4EY9I',
    appId: '1:877436752472:web:a842f75146365e9d3d702d',
    messagingSenderId: '877436752472',
    projectId: 'buddyfinal2437',
    authDomain: 'buddyfinal2437.firebaseapp.com',
    storageBucket: 'buddyfinal2437.firebasestorage.app',
  );

}