FROM python:3.13.3-slim

WORKDIR /src

COPY apps/hardware-services/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY apps/hardware-services/src/ ./

CMD ["python", "main.py"]
